### PR TITLE
Correct Ops* options

### PR DESCRIPTION
**Pull request by bra-fsn**

### CODE REVIEW

**Comment by oberstet** [comment]
@bra-fsn to complete: could you test the (merged) master branch, and if it works for you now, let me know if I should push a release. sorry, my fault, too sloppy .. I'm a bit under time pressure currently ..

**Comment by bra-fsn** [comment]
I've tested it (not fully, just the needed options).

**Comment by oberstet** [comment]
ok, let me do a quick test on my side, and if ok, I push a release

**Comment by oberstet** [comment]
@bra-fsn https://pypi.python.org/pypi/txaioetcd/0.2.2

**Comment by bra-fsn** [comment]
Thanks.

**Pull request merged**
