### PR TITLE
Introduce asyncio client

### PR DESCRIPTION
**Pull request by om26er**
execpt for watch() all other APIs are implemented

### CODE REVIEW

**Comment by om26er** [comment]
There is still more code sharing to implement but we are better than last night.

**Comment by oberstet** [comment]
this patch won't work on python 2. which we want to support: https://github.com/crossbario/txaio-etcd/blob/master/setup.py#L83

the library should not use co-routines internally, similar as AB does. that will allow users to use the library on both py 2 and 3. and if they want to restrict _their app_ to py 3 (eg as cbsh does), then they can use async/await style in their use of the library.

**Comment by om26er** [comment]
> this patch won't work on python 2. which we want to support: https://github.com/crossbario/txaio-etcd/blob/master/setup.py#L83

I'll fix that. Though the commit that I just pushed refactors the client code so that it can be cleanly used by the two backends with minimum duplication.

**Comment by om26er** [comment]
@oberstet aiohttp is python 3.4+ only so I am not sure about our options here. Thoughts ?

**Comment by oberstet** [comment]
@om26er this looks good for a first cut! we can still add things like not requiring both twisted and asyncio (install_requires) and such things, but I merge this in this stage to actually proceed with adding examples and such. Cool! Ah, and yeah, I'd be fine with py 3.4+ (if on py3/asyncio)

**Comment by om26er** [comment]
great stuff. I particularly love the code sharing between the two backends ;-)

**Comment by oberstet** [comment]
yeah, definitely. it seems slightly unpythonic to have the assembler classes and object created, used and destroyed in the function bodies, but we can still optimize those away if needed. one thing: we probably really should do some testing, manually, and mid term add some test infra and unit tests.

**Comment by oberstet** [comment]
so, I closed the corresponding issue, and filed follow up ones:

* https://github.com/crossbario/txaio-etcd/issues/19
* https://github.com/crossbario/txaio-etcd/issues/20

**Pull request merged**
